version: '3.6'
services:
  st-mariadb:
    image: library/mariadb:10.5.9
    restart: on-failure
    container_name: st-mariadb
    hostname: st-mariadb
    environment:
      MYSQL_DATABASE: 'st'
      MYSQL_ROOT_PASSWORD: 'st-root'
      MYSQL_USER: 'st-user'
      MYSQL_PASSWORD: 'st-local'
    ports:
      - 3306:3306
    volumes:
      - ./db-local-load/:/docker-entrypoint-initdb.d/:ro

  st-redis:
    image: redis:6.2.1-alpine
    restart: on-failure
    container_name: st-redis
    hostname: st-redis
    ports:
      - 6379:6379

  st-zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    restart: on-failure
    container_name: st-zookeeper
    hostname: st-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  st-kafka-1:
    image: confluentinc/cp-kafka:5.4.3
    restart: on-failure
    container_name: st-kafka-1
    hostname: st-kafka-1
    depends_on:
      - st-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'st-zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://st-kafka-1:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  st-schema-registry:
    image: confluentinc/cp-schema-registry:5.4.3
    restart: on-failure
    container_name: st-schema-registry
    hostname: st-schema-registry
    depends_on:
      - st-zookeeper
      - st-kafka-1
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 'st-schema-registry'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'st-zookeeper:2181'
